package com.naten.mobile;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
 CanvasView canvas; ArrayList<Node> nodes=new ArrayList<>(); ArrayList<String> edges=new ArrayList<>(); boolean connectMode=false; Node selected=null; int nextId=1;
 int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
 @Override public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},9);load();build();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,246,248));
  LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(12),dp(6),dp(12),dp(6));bar.setBackgroundColor(Color.rgb(31,33,36));
  TextView logo=t("AutoPilot",18,Color.WHITE);bar.addView(logo,new LinearLayout.LayoutParams(dp(85),dp(48)));
  String[] labels={"+ Trigger","+ Notification","Connect","Run","Schedule"};for(String s:labels){Button x=btn(s);bar.addView(x,new LinearLayout.LayoutParams(dp(120),dp(44)));if(s.startsWith("+ Trigger"))x.setOnClickListener(v->add("Trigger"));else if(s.startsWith("+ Notification"))x.setOnClickListener(v->add("Notification"));else if(s.equals("Connect"))x.setOnClickListener(v->{connectMode=!connectMode;selected=null;toast(connectMode?"Connect mode: tap two nodes":"Connect mode off");});else if(s.equals("Run"))x.setOnClickListener(v->{save();WorkflowStore.run(this);toast("Workflow executed");});else x.setOnClickListener(v->scheduleDialog());}
  TextView help=t("  Drag nodes. Connect: tap two nodes. Tap a notification node to edit it.",12,Color.LTGRAY);bar.addView(help,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(bar);canvas=new CanvasView(this);root.addView(canvas,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 TextView t(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(12);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackgroundColor(Color.rgb(48,50,54));return b;}
 void add(String type){Node n=new Node(nextId++,type,dp(100)+nodes.size()*dp(28),dp(100)+nodes.size()*dp(28));nodes.add(n);save();canvas.invalidate();}
 void edit(Node n){if(!"Notification".equals(n.type)){toast(n.type+" node selected");return;}LinearLayout box=new LinearLayout(this);box.setPadding(dp(18),0,dp(18),0);box.setOrientation(LinearLayout.VERTICAL);EditText title=new EditText(this);title.setHint("Title");title.setText(n.title);title.setTextColor(Color.DKGRAY);EditText msg=new EditText(this);msg.setHint("Message");msg.setText(n.message);msg.setTextColor(Color.DKGRAY);box.addView(title);box.addView(msg);new AlertDialog.Builder(this).setTitle("Notification node").setView(box).setPositiveButton("Save",(d,w)->{n.title=title.getText().toString();n.message=msg.getText().toString();save();canvas.invalidate();}).setNegativeButton("Cancel",null).show();}
 void scheduleDialog(){TimePicker p=new TimePicker(this);p.setIs24HourView(true);new AlertDialog.Builder(this).setTitle("Schedule workflow").setView(p).setPositiveButton("Schedule",(d,w)->{Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,p.getHour());c.set(Calendar.MINUTE,p.getMinute());c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);if(c.getTimeInMillis()<=System.currentTimeMillis())c.add(Calendar.DAY_OF_YEAR,1);getSharedPreferences("naten",0).edit().putLong("next",c.getTimeInMillis()).apply();ScheduleReceiver.schedule(this,c.getTimeInMillis());toast("Scheduled for "+new SimpleDateFormat("dd MMM, HH:mm",Locale.getDefault()).format(c.getTime()));}).setNegativeButton("Cancel",null).show();}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 void save(){try{JSONObject w=new JSONObject();JSONArray a=new JSONArray();for(Node n:nodes){JSONObject o=new JSONObject();o.put("id",n.id);o.put("type",n.type);o.put("x",n.x);o.put("y",n.y);o.put("title",n.title);o.put("message",n.message);a.put(o);}w.put("nodes",a);JSONArray e=new JSONArray();for(String q:edges)e.put(q);w.put("edges",e);WorkflowStore.save(this,w.toString());}catch(Exception ignored){}}
 void load(){try{JSONObject w=new JSONObject(WorkflowStore.load(this));JSONArray a=w.optJSONArray("nodes");if(a!=null)for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);Node n=new Node(o.optInt("id"),o.optString("type"),o.optInt("x",120),o.optInt("y",120));n.title=o.optString("title","AutoPilot");n.message=o.optString("message","Hello Arman");nodes.add(n);nextId=Math.max(nextId,n.id+1);}JSONArray e=w.optJSONArray("edges");if(e!=null)for(int i=0;i<e.length();i++)edges.add(e.getString(i));}catch(Exception ignored){}}
 class Node{int id;String type,title="AutoPilot",message="Hello Arman";float x,y;Node(int i,String t,float xx,float yy){id=i;type=t;x=xx;y=yy;}}
 class CanvasView extends View{Paint p=new Paint(3);Node drag;float ox,oy;CanvasView(Context c){super(c);p.setTypeface(Typeface.create("sans",0));}
  protected void onDraw(Canvas c){p.setColor(Color.rgb(230,232,235));c.drawColor(p.getColor());p.setColor(Color.rgb(210,213,218));p.setStrokeWidth(1);for(int x=0;x<getWidth();x+=dp(24))c.drawLine(x,0,x,getHeight(),p);for(int y=0;y<getHeight();y+=dp(24))c.drawLine(0,y,getWidth(),y,p);
   for(String e:edges){String[] q=e.split("->");Node a=find(Integer.parseInt(q[0])),b=find(Integer.parseInt(q[1]));if(a!=null&&b!=null){p.setColor(Color.rgb(120,124,130));p.setStrokeWidth(dp(2));c.drawLine(a.x+dp(170),a.y+dp(42),b.x,b.y+dp(42),p);}}
   for(Node n:nodes){float w=dp(170),h=dp(84);p.setColor(Color.WHITE);c.drawRoundRect(n.x,n.y,n.x+w,n.y+h,dp(8),dp(8),p);p.setColor("Trigger".equals(n.type)?Color.rgb(255,109,90):Color.rgb(100,105,112));c.drawRect(n.x,n.y,n.x+w,n.y+dp(6),p);p.setColor(Color.rgb(35,38,42));p.setTextSize(dp(15));c.drawText(n.type,n.x+dp(12),n.y+dp(32),p);p.setTextSize(dp(12));p.setColor(Color.rgb(80,84,90));c.drawText("Notification".equals(n.type)?n.message:"Start workflow",n.x+dp(12),n.y+dp(58),p);p.setColor(Color.rgb(140,144,150));c.drawCircle(n.x,n.y+dp(42),dp(5),p);c.drawCircle(n.x+w,n.y+dp(42),dp(5),p);}
  }
  Node find(int id){for(Node n:nodes)if(n.id==id)return n;return null;}
  Node hit(float x,float y){for(Node n:nodes)if(x>=n.x&&x<=n.x+dp(170)&&y>=n.y&&y<=n.y+dp(84))return n;return null;}
  public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(e.getAction()==MotionEvent.ACTION_DOWN){Node n=hit(x,y);if(n==null)return true;if(connectMode){if(selected==null){selected=n;toast("First node selected");}else if(selected!=n){String q=selected.id+"->"+n.id;if(!edges.contains(q))edges.add(q);selected=null;connectMode=false;save();invalidate();toast("Nodes connected");}return true;}drag=n;ox=x-n.x;oy=y-n.y;return true;}if(e.getAction()==MotionEvent.ACTION_MOVE&&drag!=null){drag.x=x-ox;drag.y=y-oy;invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP&&drag!=null){Node n=drag;drag=null;float nx=x-ox,ny=y-oy;boolean click=Math.abs(nx-n.x)<3&&Math.abs(ny-n.y)<3;save();if(click)edit(n);return true;}return true;}
 }
}